USE master 
GO
IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'db_unihorizonte')
	BEGIN
		ALTER DATABASE [db_unihorizonte] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
		DROP DATABASE IF EXISTS [db_unihorizonte]
	END

IF NOT EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'db_unihorizonte')
	BEGIN
		CREATE DATABASE [db_unihorizonte]
	END
GO